### ISSUE TITLE
HTMX addition

### ISSUE THREAD

**Issue by algunion** [JuliaComputing/Cobweb.jl#10]
I want to integrate HTMX closely with Cobweb.jl. 

I will do this anyway for my own needs - in one way or another - but I think it can be nice to have this in a public repo so other Julia users can benefit from it.

HTMX can already be used with Cobweb.jl (it is just a matter of adding attributes). However, I would like to add some dedicated types and functions to make the process smoother.

Would you consider a PR (given I don't touch the already implemented functionality)?

Or should I do it as a standalone extension wrapping the Cobweb.jl?

More about HTMX here: https://htmx.org/docs/

**Comment by joshday** [comment]
I'm a fan of HTMX and I toyed with an idea here: https://github.com/joshday/HTMX.jl (but I still think it's too verbose).  

If it's simple/small enough, I don't mind having the code live here.

**Comment by algunion** [comment]
OK. Since I want to implement it for myself anyway - I'd like to try it, and you can decide later if it is worth accommodating here.

**Comment by VarLad** [comment]
@joshday Do you know of a better interface, or have any specific ideas as to what the HTMX integration should look like?

**Comment by joshday** [comment]
Out of the box, there isn't much that needs to be done in terms of integration:


```html
<button hx-post="/clicked" hx-swap="outerHTML">
  Click Me
</button>
```

Is this:
```Julia
using Cobweb: h

h.button(var"hx-post"="/clicked", var"hx-swap"="outerHTML",
    "Click Me"
)
```

I'm actually surprised I haven't already done automatic translation of underscores to dashes.  I'll make that change so then it's just this:

```Julia
using Cobweb: h

h.button(hx_post="/clicked", hx_swap="outerHTML",
    "Click Me"
)
```

**Comment by VarLad** [comment]
This looks great! :grinning: 
Thanks a lot. Over time I'll try making a small demo with this and Oxygen.jl

**Comment by VarLad** [comment]
@joshday Does documenting this as a usage example somewhere, along with installing htmx sound good?
For installation, I believe this should be good enough?
```julia
head = h.head(
    h.script(
        src="https://unpkg.com/htmx.org@2.0.2",
        integrity="sha384-Y7hw+L/jvKeWIRRkqWYfPcvVxHzVzn5REgzbawhxAuQGwX1XWe70vji+VSeHOThJ",
        crossorigin="anonymous"
    )
)
```

(taken from https://htmx.org/docs/#installing )
