### ISSUE TITLE
CSS next?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaComputing/Cobweb.jl#5]
Hyperscript.jl makes styles available one way.  CSSUtil.jl, which is older and unattended afaik, does it another way.  Cobweb should do it in whatever way is consonant with your approach to making JavaScript/TypeScript available.  Just to make the project easier overall, following a pervasive logic.

**Comment by joshday** [comment]
Agreed!  I've just added some basic CSS functionality.  I'm also working on a package for writing web pages using [TailwindCSS](https://tailwindcss.com), which uses a CLI to automatically write the CSS file.
