### ISSUE TITLE
No plot is sent to the browser. Is this a Cobweb issue?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaComputing/Cobweb.jl#8]
https://github.com/JuliaComputing/PlotlyLight.jl/issues/18

**Comment by joshday** [comment]
Hmm, we use https://github.com/tpapp/DefaultApplication.jl to launch the browser, so it may actually be something in there.

Can you share your code for making the plot?

**Comment by PetrKryslUCSD** [comment]
The issue was fixed by restarting the computer. Apparently operating system issue then. Sorry for the noise. Thanks!

**Comment by joshday** [comment]
Glad to hear it resolved itself!
